version: "3.8"

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"  # exposto para acesso externo
    volumes:
      - mongo_data:/data/db
    networks:
      - shared_net

  rest:
    build: ./rest
    container_name: rest_service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - shared_net


volumes:
  mongo_data:

networks:
  shared_net:
    driver: bridge
